apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: traefik
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: traefik
  policy:
    semver:
      range: '>=3.6.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: whoami
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: whoami
  policy:
    semver:
      range: '>=1.10.0'
