apiVersion: v1
kind: Service
metadata:
  name: lobicornis
  namespace: lobicornis
  labels:
    app.kubernetes.io/name: lobicornis
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: lobicornis
